name: Nuke
main: it\cheditx\nuke\Main
version: 1.0.0
api: 4.0.0
author: cheditx
description: Boom!
commands:
  nuke:
    description: Make a nuke!
    permission: nuke.command
permissions:
  nuke.command:
    description: "Make a nuke!"
    default: op
