#plugin created by cheditx and with the help of GodzHard Telegram = @cheditx, @GodzHard

NukeAlreadyActivated: "§f[§4NUKE§f] > §aNuke already activated!"
NukeActivated: "§f[§4NUKE§f] > §aNuke activated!"
DeathByNukeMessage: "{player} §cwas killed by the nuke!"
VictimsMessage: "{victims} §cvictims! "
CountDownMessage: "§4EXPLOTION §6IN: {time}"
KeepInventory: false
ExplosionSound: true
CountDownSound: true
CountDown: 10