#plugin created by cheditx and with the help of GodzHard Telegram = @cheditx, @GodzHard

NukeActivated: "§f[§4NUKE§f] > §aNuke activated!"
DeathByNukeMessage: "{player} §cwas killed by the nuke!"
VictimsMessage: "{victims} §cvictims! "
CountDownMessage: "§4EXPLOTION §6IN: {time}"
KeepInventory: true
ExplotionSound: true
CountDownSound: true
CountDown: 10